AWSTemplateFormatVersion: 2010-09-09
Description: Template to create s3 buckets and copy files from one bucket to another

Parameters:
  MainBucketName:
    Type: String
    Description: The name of the source S3 bucket to copy files from.

  BackupBucketName:
    Type: String
    Description: The name of the destination S3 bucket to copy files to.

  LambdaRuntimeVersion:
    Type: String
    Description: Lambda runtime version to use.

  LambdaHandler:
    Type: String
    Description: Lambda function handler
  
  LambdaBucketName:
    Type: String
    Description: Name of the S3 bucket where Lambda code is stored
  
  LamdbaBucketKey:
    Type: String
    Description: S3 object key for the Lambda code zip file


Resources:
  BackupBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BackupBucketName 

  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: "arn:aws:s3:::*/*"
          PolicyName: !Sub "lambda-policy-role"

  BackupLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: BackupLambdaFunction
      Runtime: !Ref LambdaRuntimeVersion
      Role: !GetAtt LambdaFunctionRole.Arn # IAM role that Lambda will use
      Handler: !Ref LambdaHandler  # Entry point: fileName.functionName
      Environment:
        Variables:
          BACKUP_BUCKET: !Ref BackupBucketName
      Code:
        S3Bucket: !Ref LambdaBucketName
        S3Key: !Ref LamdbaBucketKey

  MainBucket:
    Type: 'AWS::S3::Bucket'
    DependsOn: LambdaInvokePermission
    Properties:
      BucketName: !Ref MainBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt BackupLambdaFunction.Arn

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn: BackupLambdaFunction
    Properties:
      FunctionName: !GetAtt BackupLambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${MainBucketName} # The ARN of the source bucket

